[build]
base = "elibot"
publish = "elibot"
functions = "elibot/netlify/functions"
command = "npm ci && node scripts/register-commands.js"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["discord-interactions", "@supabase/supabase-js", "undici"]

# להריץ את בדיקת הלוטו כל 5 דקות (אפשר לשנות ל-1 דקה אם תרצה)
[[scheduled.functions]]
  path = "cron-lottery"
  schedule = "*/5 * * * *"

