[build]
base = "elibot"                         # פה נמצא package.json שלך
publish = "elibot"                      # תיקייה שקיימת בפועל; אם אין אתר סטטי, זה עדיין חייב להתקיים
functions = "elibot/netlify/functions"  # נתיב אמיתי לפונקציות
command = "npm install --no-audit --no-fund && node scripts/register-commands.js"



[functions]
  node_bundler = "esbuild"
  external_node_modules = ["discord-interactions", "@supabase/supabase-js", "undici"]

# להריץ את בדיקת הלוטו כל 5 דקות (אפשר לשנות ל-1 דקה אם תרצה)
[[scheduled.functions]]
  path = "cron-lottery"
  schedule = "*/5 * * * *"



