[build]
base = "elibot"                         # כאן יושב package.json והסקריפט
publish = "."                           # אין אתר סטטי? נקודת הבסיס קיימת תמיד
functions = "netlify/functions"         # יחסי ל-base (כלומר elibot/netlify/functions)
command = "npm install --no-audit --no-fund && node scripts/register-commands.js"




[functions]
  node_bundler = "esbuild"
  external_node_modules = ["discord-interactions", "@supabase/supabase-js", "undici"]

# להריץ את בדיקת הלוטו כל 5 דקות (אפשר לשנות ל-1 דקה אם תרצה)
[[scheduled.functions]]
  path = "cron-lottery"
  schedule = "*/5 * * * *"




